// @flow
var url_patterns =  ["https://*/*cloudflare.min.js", 
    "https://*.youtube.com/api/stats/ads/*",
    "https://*.youtube.com/api/stats/ads*",
    "https://*.youtube.com/api/stats/qoe*",
    "https://*.youtube.com/pagead/conversion/*",
    "https://*.youtube.com/pagead/adview*",
    "https://*.youtube.com/annotations_invideo*",
    "https://consent.youtube.com/*",
    "https://consent.google.com/*",
    "https://*.cloudfront.net/*sp.js", 
    "https://*.facebook.net/*js", 
    "https://*.doubleclick.net/pagead/*",
    "https://*.doubleclick.net/gampad/*",
    "https://*.doubleclick.net/instream/*",
    "https://*.gstatic.com/youtube/img/promos/*",
    "https://*.googleadservices.net/pagead/*",
    "https://*.googletagservices.com/*gpt.js",
    "https://*.googletagservices.com/*gpt.js",
    "https://*/*www-pagead-id.js",
    "https://*/*analytics.min.js",
    "https://*/*analytics.js", 
    "https://*.fullstory.com/*fs.js", 
    "https://*.quantserve.com/*quant.js", 
    "https://pixel.quantserve.com/*", 
    "http://assets.adobedtm.com/*js",
    "http://*.collect.igodigital.com/collect.js",
    "https://fonts.googleapis.com/*",
    "https://*.gravatar.com/*",
    "https://spoor-api.ft.com/px.gif?*"
];

